#define LOWER_a     	0x1e61
#define LOWER_b     	0x3062
#define LOWER_c     	0x2e63
#define LOWER_d     	0x2064
#define LOWER_e     	0x1265
#define LOWER_f     	0x2166
#define LOWER_g     	0x2267
#define LOWER_h     	0x2368
#define LOWER_i     	0x1769
#define LOWER_j     	0x246a
#define LOWER_k     	0x256b
#define LOWER_l     	0x266c
#define LOWER_m     	0x326d
#define LOWER_n     	0x316e
#define LOWER_o     	0x186f
#define LOWER_p     	0x1970
#define LOWER_q     	0x1071
#define LOWER_r     	0x1372
#define LOWER_s     	0x1f73
#define LOWER_t     	0x1474
#define LOWER_u     	0x1675
#define LOWER_v     	0x2f76
#define LOWER_w     	0x1177
#define LOWER_x     	0x2d78
#define LOWER_y     	0x1579
#define LOWER_z     	0x2c7a
	

#define UPPER_A     	0x1e41
#define UPPER_B     	0x3042
#define UPPER_C     	0x2e43
#define UPPER_D     	0x2044
#define UPPER_E     	0x1245
#define UPPER_F     	0x2146
#define UPPER_G     	0x2247
#define UPPER_H     	0x2348
#define UPPER_I     	0x1749
#define UPPER_J     	0x244a
#define UPPER_K     	0x254b
#define UPPER_L     	0x264c
#define UPPER_M     	0x324d
#define UPPER_N     	0x314e
#define UPPER_O     	0x184f
#define UPPER_P     	0x1950
#define UPPER_Q     	0x1051
#define UPPER_R     	0x1352
#define UPPER_S     	0x1f53
#define UPPER_T     	0x1454
#define UPPER_U     	0x1655
#define UPPER_V     	0x2f56
#define UPPER_W     	0x1157
#define UPPER_X     	0x2d58
#define UPPER_Y     	0x1559
#define UPPER_Z     	0x2c5a


#define UP          	0x4800
#define DOWN        	0x5000
#define LEFT        	0x4b00
#define RIGHT         	0x4d00
#define CONTROL_LEFT    0x7300
#define CONTROL_RIGHT   0x7400

#define ESC         	0x011b
#define ENTER       	0x1c0d
#define SPACE       	0x3920
#define TAB         	0x0f09
#define DELETE      	0x5300
#define INSERT      	0x5200
	
#define HOME        	0x4700
#define END         	0x4f00
#define PAGE_UP     	0x4900
#define PAGE_DOWN   	0x5100
	
#define F1          	0x3b00
#define F2          	0x3c00
#define F3          	0x3d00
#define F4          	0x3e00
#define F5          	0x3f00
#define F6          	0x4000
#define F7          	0x4100
#define F8          	0x4200
#define F9          	0x4300
#define F10         	0x4400


#define NUM_1       	0x0231
#define NUM_2       	0x0332
#define NUM_3       	0x0433
#define NUM_4       	0x0534
#define NUM_5       	0x0635
#define NUM_6       	0x0736
#define NUM_7       	0x0837
#define NUM_8       	0x0938
#define NUM_9       	0x0a39
#define NUM_0       	0x0b30
	